### ISSUE TITLE
Can't build Korora-gnome-23

### ISSUE THREAD

**Issue by crazyusb** [kororaproject/kp-config#3]
Hi, I can't build Korora Gnome 23, because of broken dependencies 
<code>
Error creating Live CD : Failed to build transaction : openchange-2.3-6.fc23.x86_64 requiert libsamba-debug-samba4.so(SAMBA_4.3.0)(64bit)
</code>
Any idea of what to do ?

**Comment by csmart** [comment]
This is because upstream keeps breaking it.. https://bugzilla.redhat.com/show_bug.cgi?id=1277023

**Comment by csmart** [comment]
Could you please try again?

**Comment by crazyusb** [comment]
Hi sorry for the wait, I've relaunch the building, I've found the way for solving the bug by enabling the testing repo, but after 2-3 build that went well. I've launch again and I have another bug
<code>
Traceback (most recent call last):
  File "/usr/share/yum-cli/callback.py", line 136, in callback
    fd = os.open(rpmloc, os.O_RDONLY)
OSError: [Errno 2] Aucun fichier ou dossier de ce type: '/var/tmp/imgcreate-qnxC8p/install_root/var/cache/yum/Korora 23/packages/korora-release-23-2.noarch.rpm'
FATAL ERROR: python callback <bound method RPMInstallCallback.callback of <callback.RPMInstallCallback instance at 0x7f8630bbfdd0>> failed, aborting!
</code>
Have you any  idea ?

**Comment by csmart** [comment]
OK so you built successfully a few times, but later it failed? It can't find the korora-release rpm to install for some reason.

Might have been a once off, have you tried since then?

**Comment by crazyusb** [comment]
I've tried couple of times today at least 5

Le jeu. 14 janv. 2016 23:27, Chris Smart <notifications@github.com> a
écrit :

**Comment by csmart** [comment]
Can you please post your kp.conf file and the command you ran?
